[GENERAL]
REF_GENOME = $RESOURCES/grch37/genome/grch37.fa
REF_DICT = $RESOURCES/grch37/genome/grch37.dict
TARGETS_VARCAL = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.bed
TARGETS_DOC = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.bed
TARGETS_PCR = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.interval_list
DBSNP = $RESOURCES/grch37/dbsnp/dbsnp_b155.vcf.gz
CDS_TARGET = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.interval_list
TEMP_DIR = $SLURM_TMPDIR

[GATK]

BASE_RECALIBRATOR_JAVA_OPTIONS = "-Djava.io.tmpdir=/tmp -Xmx40g"
BQSR_JAVA_OPTIONS = "-Djava.io.tmpdir=/tmp -Xmx24g"
HAPLOTYPE_CALLER_JAVA_OPTIONS =  "-Xmx46G"
COMBINE_GVCF_JAVA_OPTIONS = "-Xmx32G"
GENOTYPE_GVCF_JAVA_OPTIONS = "-Xmx4G -XX:+UseParallelGC -XX:ParallelGCThreads=10"
VARIANT_RECALIBRATOR_SNP_JAVA_OPTIONS = "-Xmx24g"
VQSR_SNP_JAVA_OPTIONS = "-Xmx24g"
VARIANT_RECALIBRATOR_INDEL_JAVA_OPTIONS = "-Xmx24g"
VQSR_INDEL_JAVA_OPTIONS = "-Xmx24g"

[BAM_TO_CNV]
NCBI_TO_REFSEQ = $RESOURCES/grch37/ncbi/assembly/GCF_000001405.25_GRCh37.p13_ncbi_to_refseq.tsv
TARGETS_CNV_GENE = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.gatkcnv.preprocessed.interval_list
TARGETS_CNV_ANNOTATED = $RESOURCES/grch37/ucsc/refseq/v20231002/refseq_curated_all_exons_sort.gatkcnv.preprocessed.annotated.tsv
PLOIDY_PRIORS_TABLE = $RESOURCES/grch37/cnv_model/contig_ploidy_prior_hg19.tsv
CNV_MODEL = $RESOURCES/grch37/cnv_model/cnv_model_all_exons/bam_to_cnv/cnvs_cohort-model
CNV_PLOIDY_MODEL = $RESOURCES/grch37/cnv_model/cnv_model_all_exons/bam_to_cnv/ploidy-model

[TOOLS]
BIN = $BIN

[BAM_TO_VCF]
VARIANT_CALLER = GATK
VARIANT_CALLER_PATH = $BIN/gatk
HAPMAP = $RESOURCES/grch37/genome/annotations/hapmap_3.3.b37.vcf.gz
OMNI = $RESOURCES/grch37/genome/annotations/1000G_omni2.5.b37.vcf.gz
SNP1000G = $RESOURCES/grch37/genome/annotations/1000G_phase1.snps.high_confidence.b37.vcf.gz
MILLS = $RESOURCES/grch37/genome/annotations/Mills_and_1000G_gold_standard.indels.b37.vcf.gz

[COLLECT_QC]
DEPTH_OF_COVERAGE_MIN_BASE_QUALITY = 20
DEPTH_OF_COVERAGE_MIN_MAPPING_QUALITY = 20	
DEPTH_OF_COVERAGE_INTERVAL_PADDING = 10
DEPTH_OF_COVERAGE_THRESHOLD = 20,100
DEPTH_OF_COVERAGE_OMIT_BASE_OUTPUT = True
DEPTH_OF_COVERAGE_JAVA_OPTIONS = "-Xmx1g"

[ANNOTATE_VCF]
ANNOTATION_TOOL = snpeff
SNPEFF = $BIN/snpeff/snpEff.jar
SNPEFF_CONFIG = $BIN/snpeff/snpEff.config
SNPEFF_GENOME = GRCh37.p13
SNPEFF_JAVA_OPTIONS = "-Djava.io.tmpdir=/tmp -Xmx20G"
VCFANNO_CONFIG = $BIN/ngstk/vcfanno_config_grch37.toml
VCFANNO_CONFIG_VARIABLE = $RESOURCES
VCFANNO_OPTIONS = -p 6

[FILTER_VCF]
DEPTH_MIN = 10
DEPTH_ALT_MIN = 3
ALT_FREQ_MIN = 0.05
PASS_ONLY = False 
CLINVAR_SIG = Pathogenic,Likely_pathogenic,Pathogenic/Likely_pathogenic,drug_response
CLINVAR_SIG_CONF =
GNOMAD_AF_MAX = 0.01
VARIANT_CODING = True
VARIANT_LOF = False
IGNORE_VARIANTS = 
MAX_SAMPLE_COUNT = 5

[REPORT_VARIANTS]
GENE_PANEL = 
CANONICAL_REFSEQ = $RESOURCES/grch37/ucsc/canonical.refseq.tsv
GNOMAD_METRICS = $RESOURCES/grch37/gnomad/gnomad.lof_metrics.by_gene.txt
HGNC_GENES = $RESOURCES/hgnc/hgnc_complete_set.txt
HPO_GENES = $RESOURCES/hpo/genes_for_HP_0000001.csv
HPO_DISEASES = $RESOURCES/hpo/mode_inheritance/diseases_for_HP_0000001.tsv
HPO_GENES_DISEASES = $RESOURCES/hpo_new/hpo_genes_diseases.tsv
HPO_DISEASE_INHERITANCES = $RESOURCES/hpo/diseases_inheritence.csv
DENOVO_MINIMUM_DEPTH_PROBAND = 10
DENOVO_MINIMUM_DEPTH_PARENTS = 10
DENOVO_MINIMUM_ALT_DEPTH_PROBAND = 4
DENOVO_MAXIMUM_ALT_DEPTH_PARENTS = 2
DENOVO_MINIMUM_ALT_AF_PROBAND = 0.2
DENOVO_MAXIMUM_ALT_AF_PARENTS = 0.05

[POLYT_TG_COUNTS]
POLYT_TG_IS_ACTIVE = True

[REPORT_VARIANTS_COLUMNS]
SAMPLE_ID = True
POSITION = True 
ALLELES = True 
SAMPLE_GT = True 
SAMPLE_GT_QUAL = True 
FILTER = True 
SAMPLE_DEPTH = True 
SAMPLE_DEPTH_REF = True 
SAMPLE_DEPTH_ALT = True 
SAMPLE_ALT_AF = True 
VARIANT_GENE_NAME = True 
GENE_LIST = False 
VARIANT_ANNOTATION = True 
VARIANT_HGVS_C = True 
VARIANT_HGVS_P = True 
CANONICAL_HGVS_C = True 
CANONICAL_HGVS_P = True
SELECT_HGVS_C = True
SELECT_HGVS_P = True
VARIANT_CODING = True
VARIANT_LOF = True 
DBSNP_ID = True 
CLINVAR_ID = True 
CLINVAR_SIG = True 
CLINVAR_SIG_CONF = True 
CLINVAR_DN = True 
CLINVAR_REVSTAT = True 
COSMIC_ID = True 
COSMIC_GENE = True 
COSMIC_CDS = True 
COSMIC_AA = True 
COSMIC_CNT = True 
GNOMAD_POS = True 
GNOMAD_AC = True 
GNOMAD_AN = True
GNOMAD_AF = True 
GNOMAD_HOM = True 
GNOMAD_FILT = True 
GNOMAD_EX_AC = True 
GNOMAD_EX_AN = True 
GNOMAD_EX_AF = True 
GNOMAD_EX_HOM = True 
GNOMAD_EX_FILT = True 
GNOMAD_WG_AC = True 
GNOMAD_WG_AN = True 
GNOMAD_WG_AF = True 
GNOMAD_WG_HOM = True 
GNOMAD_WG_FILT = True 
GNOMAD_WG_POPMAX = True 
GNOMAD_WG_AN_POPMAX = True
GNOMAD_WG_AC_POPMAX = True 
GNOMAD_WG_AF_POPMAX = True 
GNOMAD_WG_NHOM_POPMAX = True 
GNOMAD_EX_POPMAX = True 
GNOMAD_EX_AN_POPMAX = True 
GNOMAD_EX_AC_POPMAX = True 
GNOMAD_EX_AF_POPMAX = True 
GNOMAD_EX_NHOM_POPMAX = True 
SEGDUP = True 
REP_MASK = True
REP_SIMPLE = True
#NOTSURE, matched VIDO
CADD_RAW = False 
CADD_PHRED = True 
#NOTSURE, matched VIDO
REMM = False
REVEL = True 
SPLICEAI_GENE = True
SPLICEAI_DS_MAX = True
SPLICEAI_TYPE = True
SPLICEAI_POS = True
PRIMATEAI = True
#NOTSURE, matched VIDO
DBSCSNV_ADA = False 
DBSCSNV_RF = False  
GNOMAD_SYN_Z = True 
GNOMAD_MIS_Z = True 
GNOMAD_LOF_Z = True 
HPO_DISEASE = True 
VARIANT_NUM_CALLED = True 
VARIANT_NUM_HOM_REF = True 
VARIANT_NUM_HET = True
VARIANT_NUM_HOM_ALT = True 
VARIANT_NUM_UNKNOWN = True 
DENOVO = False 
RECESSIVE = False 
PHASING = False
GENE_COUNT = False 
COMMENTS = True
VARIANT_EXON_INTRON = False
CADD_PHRED_SNV = False
CADD_PHRED_INDEL = False
BAYESDEL_NO_AF_SCORE = False
BAYESDEL_ADD_AF_SCORE = False
METASVM_SCORE = False
METALR_SCORE = False
METARNN_SCORE = False
GNOMAD_EX_NON_CANCER_AF = False
AM_SCORE = False
AM_CLASS = False
